### ISSUE TITLE
Clicking on notebook resource should (somehow) open notebook in jupyterlab

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#310] opened 2021-11-30 10:47 UTC
Think this was mentioned elsewhere, but good to put as separate issue. 

In Jupyterlab any notebook files are clearly listed on the left, and as with NWB files, a user will reasonably expect thta clicking on one of these will open the notebook, and even the tooltip says this:
<img width="603" alt="Screenshot 2021-11-30 at 10 43 54" src="https://user-images.githubusercontent.com/1556687/144033135-c95d63d4-8dd3-42be-9379-125a7fe73385.png">

It will require a deeper interaction with jupyterlab though, the full interface shouldn't be reloaded, just a new panel/window opened with the notebook, within the existing session.

**Comment by filippomc** [comment] 2021-12-01 15:13
Closing as duplicate of #302

**Closed by filippomc** 2021-12-01 15:13 UTC
